"""`.env.active` must mean the same thing to every consumer that reads it.

The file generated by ``scripts/env_profile.sh`` has three readers: make targets
``.``-source it, ``docker compose --env-file`` parses it, and the app loads it
through python-dotenv. A value those readers disagree about is worse than a
rejected one — the worker silently gets a different secret and MinIO or Docling
answers 403 a long way from the cause.

Single quotes are the closest thing to a common form, but not a universal one:
python-dotenv unescapes ``\\\\`` inside them and the shell does not, and neither
a literal ``'`` nor a trailing backslash can be expressed at all. So the
serializer rejects those characters, and these tests hold it to that.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from dotenv import dotenv_values

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "env_profile.sh"

LOCAL_ENV_TEMPLATE = """\
PI_LOCAL_MINIO_ENDPOINT='localhost:9000'
PI_LOCAL_MINIO_ACCESS_KEY='minioadmin'
PI_LOCAL_MINIO_SECRET_KEY={secret}
PI_LOCAL_REDIS_URL='redis://localhost:6379/1'
PI_LOCAL_POSTGRES_DSN='postgresql://pageindex:pageindex@localhost:5432/pageindex'
PI_LOCAL_DOCLING_URL='http://localhost:8080'
PI_LOCAL_DOCLING_TOKEN=''
"""


def _run(tmp_path: Path, secret_literal: str) -> subprocess.CompletedProcess[str]:
    """Generate a profile in an isolated repo root holding `secret_literal`.

    `secret_literal` goes into env/local.env verbatim — including its quoting —
    because how the *input* layer is quoted is part of what is under test.
    """
    (tmp_path / "env").mkdir(exist_ok=True)
    (tmp_path / "scripts").mkdir(exist_ok=True)
    (tmp_path / "scripts" / "env_profile.sh").write_bytes(SCRIPT.read_bytes())
    (tmp_path / ".env").write_text("FOO='bar'\n")
    (tmp_path / "env" / "local.env").write_text(
        LOCAL_ENV_TEMPLATE.format(secret=secret_literal)
    )
    return subprocess.run(
        ["bash", "scripts/env_profile.sh"],
        cwd=tmp_path, capture_output=True, text=True,
        env={"PATH": "/usr/bin:/bin", "PI_PROFILE": "local"},
    )


def _shell_value(env_file: Path, key: str) -> str:
    """Read `key` the way a make target does — by `.`-sourcing the file."""
    return subprocess.run(
        ["bash", "-c", f'. "{env_file}" >/dev/null 2>&1; printf "%s" "${key}"'],
        capture_output=True, text=True,
    ).stdout


# Values a shell and python-dotenv are known to agree on once single-quoted:
# none of $, `, ", #, whitespace or = carry meaning inside single quotes.
@pytest.mark.parametrize("secret", [
    "plainsecret",
    "p@ss w0rd with spaces",
    'has$dollar`backtick"dquote#hash',
    "has=equals;semi|pipe&amp",
    "sk-proj-AbC123_-.~",
])
def test_generated_value_reads_identically_via_shell_and_dotenv(tmp_path, secret):
    # Arrange / Act
    proc = _run(tmp_path, f"'{secret}'")

    # Assert
    assert proc.returncode == 0, proc.stderr
    out = tmp_path / ".env.active"
    assert dotenv_values(out)["MINIO_SECRET_KEY"] == secret
    assert _shell_value(out, "MINIO_SECRET_KEY") == secret


def test_sourcing_the_generated_file_does_not_execute_embedded_code(tmp_path):
    # Arrange: a value that would run a command if it were double-quoted.
    marker = tmp_path / "PWNED"
    # Act
    proc = _run(tmp_path, f"'x$(touch {marker})y'")

    # Assert
    assert proc.returncode == 0, proc.stderr
    _shell_value(tmp_path / ".env.active", "MINIO_SECRET_KEY")
    assert not marker.exists(), "command substitution ran when the file was sourced"


@pytest.mark.parametrize("secret,description", [
    ('"p\'ss"', "a literal single quote cannot be expressed for dotenv"),
    (r"'ab\\cd'", r"dotenv unescapes \\ inside single quotes, the shell does not"),
    (r"'trailing\\'", "a trailing backslash makes the dotenv line unparseable"),
])
def test_unrepresentable_secret_is_rejected_rather_than_silently_corrupted(
    tmp_path, secret, description
):
    # Act
    proc = _run(tmp_path, secret)

    # Assert
    assert proc.returncode != 0, f"should have been rejected: {description}"
    assert "single quote or backslash" in proc.stderr
    assert not (tmp_path / ".env.active").exists(), "wrote a profile it rejected"


def test_unparsable_input_layer_fails_loudly_instead_of_emitting_empty_values(tmp_path):
    """An unbalanced quote in a layer used to abort the source and yield ''.

    Every lookup then returned empty, so the profile was written with blank
    credentials and the failure surfaced later as an unexplained 403.
    """
    # Arrange: unquoted value containing ' — an unterminated string.
    # Act
    proc = _run(tmp_path, "p'ss")

    # Assert
    assert proc.returncode != 0
    assert "not valid shell" in proc.stderr
    assert not (tmp_path / ".env.active").exists()


def test_rejection_leaves_no_partial_or_temporary_profile_behind(tmp_path):
    """A truncated .env.active is worse than none — it is what make sources."""
    # Act
    proc = _run(tmp_path, r"'ab\\cd'")

    # Assert
    assert proc.returncode != 0
    leftovers = sorted(p.name for p in tmp_path.glob(".env.active*"))
    assert leftovers == [], f"left behind: {leftovers}"
