"""`.env.active` must mean the same thing to every consumer that reads it.

The file generated by ``scripts/env_profile.sh`` has three readers: make targets
``.``-source it, ``docker compose --env-file`` parses it, and the app loads it
through python-dotenv. A value those readers disagree about is worse than a
rejected one — the worker silently gets a different secret and MinIO or Docling
answers 403 a long way from the cause.

Single quotes are the closest thing to a common form, but not a universal one:
python-dotenv unescapes ``\\\\`` inside them and the shell does not, and neither
a literal ``'`` nor a trailing backslash can be expressed at all. So the
serializer rejects those characters, and these tests hold it to that.
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest
from dotenv import dotenv_values

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "env_profile.sh"

LOCAL_ENV_TEMPLATE = """\
PI_LOCAL_MINIO_ENDPOINT='localhost:9000'
PI_LOCAL_MINIO_ACCESS_KEY='minioadmin'
PI_LOCAL_MINIO_SECRET_KEY={secret}
PI_LOCAL_REDIS_URL='redis://localhost:6379/1'
PI_LOCAL_POSTGRES_DSN='postgresql://pageindex:pageindex@localhost:5432/pageindex'
PI_LOCAL_DOCLING_URL='http://localhost:8080'
PI_LOCAL_DOCLING_TOKEN=''
"""


def _run(
    tmp_path: Path,
    secret_literal: str = "'plainsecret'",
    base_env: str = "FOO='bar'\n",
    remote_env: str | None = None,
    path: str | None = None,
) -> subprocess.CompletedProcess[str]:
    """Generate a profile in an isolated repo root holding `secret_literal`.

    `secret_literal` goes into env/local.env verbatim — including its quoting —
    because how the *input* layer is quoted is part of what is under test.
    """
    (tmp_path / "env").mkdir(exist_ok=True)
    (tmp_path / "scripts").mkdir(exist_ok=True)
    (tmp_path / "scripts" / "env_profile.sh").write_bytes(SCRIPT.read_bytes())
    (tmp_path / ".env").write_text(base_env)
    (tmp_path / "env" / "local.env").write_text(
        LOCAL_ENV_TEMPLATE.format(secret=secret_literal)
    )
    if remote_env is not None:
        (tmp_path / "env" / "remote.env").write_text(remote_env)
    # Inherit the real environment rather than pinning PATH. The script shells
    # out to `ip` on this path, and a hand-built PATH that misses it would make
    # every test here pass or fail for a reason unrelated to serialization —
    # the reject cases especially, which would see a non-zero exit from the
    # wrong cause. PI_* is cleared so an operator's own toggles cannot leak in.
    env = {k: v for k, v in os.environ.items() if not k.startswith("PI_")}
    env["PI_PROFILE"] = "local"
    if path is not None:
        env["PATH"] = path
    return subprocess.run(
        ["bash", "scripts/env_profile.sh"],
        cwd=tmp_path, capture_output=True, text=True, env=env,
    )


def _shell_value(env_file: Path, key: str) -> str:
    """Read `key` the way a make target does — by `.`-sourcing the file."""
    return subprocess.run(
        ["bash", "-c", f'. "{env_file}" >/dev/null 2>&1; printf "%s" "${key}"'],
        capture_output=True, text=True,
    ).stdout


# Values a shell and python-dotenv are known to agree on once single-quoted:
# none of $, `, ", #, whitespace or = carry meaning inside single quotes.
@pytest.mark.parametrize("secret", [
    "plainsecret",
    "p@ss w0rd with spaces",
    'has$dollar`backtick"dquote#hash',
    "has=equals;semi|pipe&amp",
    "sk-proj-AbC123_-.~",
])
def test_generated_value_reads_identically_via_shell_and_dotenv(tmp_path, secret):
    # Arrange / Act
    proc = _run(tmp_path, f"'{secret}'")

    # Assert
    assert proc.returncode == 0, proc.stderr
    out = tmp_path / ".env.active"
    assert dotenv_values(out)["MINIO_SECRET_KEY"] == secret
    assert _shell_value(out, "MINIO_SECRET_KEY") == secret


def test_sourcing_the_generated_file_does_not_execute_embedded_code(tmp_path):
    # Arrange: a value that would run a command if it were double-quoted.
    marker = tmp_path / "PWNED"
    # Act
    proc = _run(tmp_path, f"'x$(touch {marker})y'")

    # Assert
    assert proc.returncode == 0, proc.stderr
    _shell_value(tmp_path / ".env.active", "MINIO_SECRET_KEY")
    assert not marker.exists(), "command substitution ran when the file was sourced"


@pytest.mark.parametrize("secret,description", [
    ('"p\'ss"', "a literal single quote cannot be expressed for dotenv"),
    (r"'ab\\cd'", r"dotenv unescapes \\ inside single quotes, the shell does not"),
    (r"'trailing\\'", "a trailing backslash makes the dotenv line unparseable"),
])
def test_unrepresentable_secret_is_rejected_rather_than_silently_corrupted(
    tmp_path, secret, description
):
    # Act
    proc = _run(tmp_path, secret)

    # Assert
    assert proc.returncode != 0, f"should have been rejected: {description}"
    assert "single quote or backslash" in proc.stderr
    assert not (tmp_path / ".env.active").exists(), "wrote a profile it rejected"


def test_unparsable_input_layer_fails_loudly_instead_of_emitting_empty_values(tmp_path):
    """An unbalanced quote in a layer used to abort the source and yield ''.

    Every lookup then returned empty, so the profile was written with blank
    credentials and the failure surfaced later as an unexplained 403.
    """
    # Arrange: unquoted value containing ' — an unterminated string.
    # Act
    proc = _run(tmp_path, "p'ss")

    # Assert
    assert proc.returncode != 0
    assert "not valid shell" in proc.stderr
    assert not (tmp_path / ".env.active").exists()


def test_rejection_leaves_no_partial_or_temporary_profile_behind(tmp_path):
    """A truncated .env.active is worse than none — it is what make sources."""
    # Act
    proc = _run(tmp_path, r"'ab\\cd'")

    # Assert
    assert proc.returncode != 0
    leftovers = sorted(p.name for p in tmp_path.glob(".env.active*"))
    assert leftovers == [], f"left behind: {leftovers}"


@pytest.mark.parametrize("base_env,description", [
    ("", "an empty base file"),
    ("MINIO_ENDPOINT='x'\nREDIS_URL='y'\n", "a base file of only managed keys"),
])
def test_base_file_with_nothing_to_carry_over_still_generates(
    tmp_path, base_env, description
):
    """`grep -v` exits 1 when it filters everything out, which set -e treats
    as failure — but both of these are legitimate base files."""
    # Act
    proc = _run(tmp_path, base_env=base_env)

    # Assert
    assert proc.returncode == 0, f"{description} aborted: {proc.stderr}"
    assert dotenv_values(tmp_path / ".env.active")["MINIO_SECRET_KEY"] == "plainsecret"


def test_local_profile_ignores_a_malformed_remote_layer(tmp_path):
    """PROFILE=local touches no remote service, so a stale env/remote.env from
    an old cluster must not block generating an offline profile."""
    # Arrange: unbalanced quote — unparsable as shell.
    # Act
    proc = _run(tmp_path, remote_env="PI_REMOTE_MINIO_SECRET_KEY='oops\n")

    # Assert
    assert proc.returncode == 0, proc.stderr
    assert dotenv_values(tmp_path / ".env.active")["MINIO_ENDPOINT"] == "localhost:9000"


def test_generation_does_not_require_iproute2(tmp_path):
    """`ip` is Linux-only; it is absent on macOS and on slim images. Under
    `set -o pipefail` a missing binary aborted the run at rc=127, with the
    reason swallowed by the 2>/dev/null on that same call."""
    # Arrange: mirror the real PATH minus `ip`. Enumerating the tools the
    # script needs by hand would be brittle in the same way the pinned PATH
    # was — a missing one fails the test for the wrong reason.
    bin_dir = tmp_path / "fakebin"
    bin_dir.mkdir()
    for d in os.environ.get("PATH", "").split(os.pathsep):
        if not d or not os.path.isdir(d):
            continue
        for entry in os.listdir(d):
            if entry == "ip" or (bin_dir / entry).exists():
                continue
            try:
                (bin_dir / entry).symlink_to(Path(d) / entry)
            except OSError:
                pass
    assert shutil.which("ip", path=str(bin_dir)) is None, "fake PATH still has ip"

    # Act
    proc = _run(tmp_path, path=str(bin_dir))

    # Assert
    assert proc.returncode == 0, f"aborted without iproute2: {proc.stderr}"
    # Falls back to the stock docker0 gateway rather than failing.
    assert dotenv_values(tmp_path / ".env.active")["MINIO_PRESIGN_ENDPOINT"] \
        == "172.17.0.1:9000"
