#!/usr/bin/env python3
"""Keep .agents/{rfcs,designs,tasks} mark-ready before a Confluence sync.

WHY: mark (kovetskiy/mark) requires `Space`/`Title`/`Folder` metadata comments
on every file it pushes, and this repo's convention is that every RFC has a
companion design doc and task-plan doc. Without this script, a freshly created
RFC-NNN with no matching design-rfcNNN/tasks-rfcNNN file either breaks `mark`
(missing headers) or silently never gets a design/tasks page created.

This script is idempotent: files that already have headers / companions are
left untouched. Run before every `mark` invocation (see scripts/confluence_sync.sh).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

AGENTS_DIR = Path(__file__).resolve().parent.parent / ".agents"
RFCS_DIR = AGENTS_DIR / "rfcs"
DESIGNS_DIR = AGENTS_DIR / "designs"
TASKS_DIR = AGENTS_DIR / "tasks"

SPACE = "CITRA"
RFC_FILE_RE = re.compile(r"^(\d+)-(.+)\.md$")

HEADER_RE = re.compile(r"<!--\s*Space:", re.IGNORECASE)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def first_h1(text: str) -> str | None:
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return m.group(1).strip() if m else None


def has_mark_headers(text: str) -> bool:
    return bool(HEADER_RE.search(text))


def inject_headers(path: Path, parent: str, title: str) -> None:
    """Prepend mark metadata comments to a file that lacks them.

    RFCs/Designs/Tasks are Confluence Cloud *folders*, not pages — mark only
    resolves `Parent` against pages, so a folder-named `Parent` silently
    creates a stray sibling page instead of attaching under the folder.
    `Folder` is mark's dedicated header for this (Cloud-only, which matches
    this workspace).
    """
    text = read(path)
    header = f"<!-- Space: {SPACE} -->\n\n<!-- Title: {title} -->\n\n<!-- Folder: {parent} -->\n\n"
    path.write_text(header + text, encoding="utf-8")
    print(f"[headers] added mark metadata to {path.relative_to(AGENTS_DIR.parent)}")


def ensure_headers(directory: Path, parent: str, title_fn) -> None:
    for path in sorted(directory.glob("*.md")):
        if path.name.endswith("-metadata.md"):
            continue
        text = read(path)
        if has_mark_headers(text):
            continue
        title = title_fn(path, text)
        inject_headers(path, parent, title)


def rfc_id_slug(path: Path) -> tuple[str, str] | None:
    m = RFC_FILE_RE.match(path.name)
    if not m:
        return None
    return m.group(1), m.group(2)


def rfc_title(rfc_id: str, slug: str, text: str) -> str:
    h1 = first_h1(text)
    if h1:
        return h1
    return f"RFC-{rfc_id}: {slug.replace('-', ' ').title()}"


DESIGN_STUB = """<!-- Space: {space} -->

<!-- Title: Design: {readable} -->

<!-- Folder: Designs -->

# Design: {readable}

| Artifact | Reference |
|---|---|
| Governing RFC | [RFC-{rfc_id}: {readable}](../rfcs/{rfc_id}-{slug}.md) |
| PRD / Requirements | `PRD.md` |
| Architecture Doc | `ARCHITECTURE.md` |
| Implementation Plan | [tasks-rfc{rfc_id}-{slug}.md](../tasks/tasks-rfc{rfc_id}-{slug}.md) |

> Stub auto-generated by scripts/confluence_scaffold.py — fill in before review.
"""

TASKS_STUB = """<!-- Space: {space} -->

<!-- Title: Implementation Plan: {readable} -->

<!-- Folder: Tasks -->

# Implementation Plan: {readable}

| Artifact | Reference |
|---|---|
| Governing RFC(s) | [RFC-{rfc_id}: {readable}](../rfcs/{rfc_id}-{slug}.md) |
| Design Document | [Design: {readable}](../designs/design-rfc{rfc_id}-{slug}.md) |
| PRD / Requirements | `PRD.md` |

> Stub auto-generated by scripts/confluence_scaffold.py — fill in before execution.
"""


RECENT_RFC_FLOOR = 11  # RFC-007..010 already have hand-written companions;
# RFC-000..006 predate the design/tasks-doc convention entirely and must
# never be auto-scaffolded. Only RFCs at/after this floor (the next one
# created after this script existed) get stubs auto-created; anything older
# that's still missing a companion only gets a warning.


def ensure_companion(
    directory: Path,
    glob_pattern: str,
    stub_path: Path,
    template: str,
    rfc_id: str,
    slug: str,
    readable: str,
    auto_create: bool,
) -> None:
    # Match by RFC id only: existing companions may use a shorter/different
    # slug than the RFC file itself (e.g. rfcs/007-docstore-data-integrity-
    # hardening.md -> designs/design-rfc007-docstore-integrity.md), so an
    # exact-slug filename match would create a spurious duplicate stub.
    if any(directory.glob(glob_pattern.format(rfc_id=rfc_id))):
        return
    if not auto_create:
        print(
            f"[WARN] no companion matching {glob_pattern.format(rfc_id=rfc_id)!r} in "
            f"{directory.relative_to(AGENTS_DIR.parent)}/ — create by hand if one is needed",
            file=sys.stderr,
        )
        return
    stub_path.write_text(
        template.format(space=SPACE, rfc_id=rfc_id, slug=slug, readable=readable),
        encoding="utf-8",
    )
    print(f"[scaffold] created {stub_path.relative_to(AGENTS_DIR.parent)}")


def ensure_companions() -> None:
    for rfc_path in sorted(RFCS_DIR.glob("*.md")):
        if rfc_path.name.endswith("-metadata.md"):
            continue
        parsed = rfc_id_slug(rfc_path)
        if not parsed:
            continue
        rfc_id, slug = parsed
        auto_create = int(rfc_id) >= RECENT_RFC_FLOOR
        readable = rfc_title(rfc_id, slug, read(rfc_path)).split(": ", 1)[-1]

        design_path = DESIGNS_DIR / f"design-rfc{rfc_id}-{slug}.md"
        tasks_path = TASKS_DIR / f"tasks-rfc{rfc_id}-{slug}.md"

        ensure_companion(
            DESIGNS_DIR,
            "design-rfc{rfc_id}-*.md",
            design_path,
            DESIGN_STUB,
            rfc_id,
            slug,
            readable,
            auto_create,
        )
        ensure_companion(
            TASKS_DIR,
            "tasks-rfc{rfc_id}-*.md",
            tasks_path,
            TASKS_STUB,
            rfc_id,
            slug,
            readable,
            auto_create,
        )


def rfc_title_for_path(path: Path, text: str) -> str:
    parsed = rfc_id_slug(path)
    if not parsed:
        return path.stem
    rfc_id, slug = parsed
    return rfc_title(rfc_id, slug, text)


def main() -> int:
    ensure_headers(RFCS_DIR, "RFCs", rfc_title_for_path)
    ensure_companions()
    ensure_headers(DESIGNS_DIR, "Designs", lambda p, t: first_h1(t) or p.stem)
    ensure_headers(TASKS_DIR, "Tasks", lambda p, t: first_h1(t) or p.stem)
    return 0


if __name__ == "__main__":
    sys.exit(main())
