#!/usr/bin/env bash
# make_remote_env.sh — snapshot the shared k3s `infra` namespace into
# env/remote.env, the "remote" side of every toggle in scripts/env_profile.sh.
#
#   ./scripts/make_remote_env.sh              # writes env/remote.env
#   ./scripts/make_remote_env.sh /tmp/foo.env # writes elsewhere
#
# Run this ON the k3s node (it needs kubectl). To test from a laptop, copy the
# generated file over — it is self-contained and holds no ClusterIP dependency
# beyond the cluster-side endpoints, which env_profile.sh will skip when they
# are unreachable.
#
# Secrets are read from the cluster at generation time; none are stored in this
# script. The output is gitignored — treat it as a credential file.
set -euo pipefail

cd "$(dirname "$0")/.."

NS="${INFRA_NAMESPACE:-infra}"
OUT="${1:-env/remote.env}"
BASE="${BASE_ENV:-.env}"

# Public HTTPS host for MinIO — the host a presigned URL names so the remote
# Docling service can fetch the object.
PUBLIC="${PI_REMOTE_MINIO_PUBLIC_ENDPOINT:-infra.saliltrehan.com}"

# Route prefix the public MinIO S3 API is served under. Traefik strips it
# before MinIO sees the request, which is exactly why this works: MinIO
# verifies the SigV4 signature against the stripped path — the same path the
# SDK signs — so the prefix is spliced in *after* signing. Verified live:
# https://<PUBLIC>/minio/<bucket>/<key>?<sig> returns 200, while the unprefixed
# signed path 404s at Traefik and an unsigned request gets 403 from MinIO.
PRESIGN_PREFIX="${PI_REMOTE_MINIO_PRESIGN_PATH_PREFIX:-/minio}"

command -v kubectl >/dev/null || { echo "missing required tool: kubectl" >&2; exit 1; }

secret() { kubectl get secret infra-secrets -n "$NS" -o "jsonpath={.data.$1}" | base64 -d; }
svc_ip() { kubectl get svc "$1" -n "$NS" -o jsonpath='{.spec.clusterIP}'; }

MINIO_IP="$(svc_ip minio)"
REDIS_IP="$(svc_ip redis)"
# postgres is a headless StatefulSet service, so resolve the pod IP directly.
# It changes on pod restart — rerun this script after any churn.
PG_IP="$(kubectl get pod -n "$NS" -l app=postgres -o jsonpath='{.items[0].status.podIP}')"

MINIO_USER="$(secret MINIO_ROOT_USER)"
MINIO_PASS="$(secret MINIO_ROOT_PASSWORD)"
PG_USER="$(secret POSTGRES_USER)"
PG_PASS="$(secret POSTGRES_PASSWORD)"

# The Scaleway Docling endpoint is not a cluster resource; carry it over from
# .env so the credential lives in exactly one place.
doc_val() { ( set -a; . "$BASE" >/dev/null 2>&1 || true; set +a; printf '%s' "${!1-}" ); }
DOCLING_URL="${PI_REMOTE_DOCLING_URL:-$(doc_val DOCLING_SERVICE_URL)}"
DOCLING_TOKEN="${PI_REMOTE_DOCLING_TOKEN:-$(doc_val DOCLING_SERVICE_BEARER_TOKEN)}"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# env/remote.env — generated by scripts/make_remote_env.sh on $(date -u +%FT%TZ)
# from the k3s '$NS' namespace. Credential file: gitignored, mode 600.
# Regenerate after any cluster IP change (especially a postgres pod restart).

# In-cluster address: fast, but only routable on the k3s node itself.
PI_REMOTE_MINIO_CLUSTER_ENDPOINT=${MINIO_IP}:9000
# Public HTTPS address the remote Docling service fetches presigned URLs from.
# Presign-only: the SDK refuses a path in an endpoint ("path in endpoint is not
# allowed"), so direct S3 calls cannot use the prefixed route — see
# docs/ENV_PROFILES.md.
PI_REMOTE_MINIO_PUBLIC_ENDPOINT=${PUBLIC}
PI_REMOTE_MINIO_PRESIGN_PATH_PREFIX=${PRESIGN_PREFIX}
PI_REMOTE_MINIO_ACCESS_KEY=${MINIO_USER}
PI_REMOTE_MINIO_SECRET_KEY=${MINIO_PASS}

PI_REMOTE_REDIS_URL=redis://${REDIS_IP}:6379/1
PI_REMOTE_POSTGRES_DSN=postgresql://${PG_USER}:${PG_PASS}@${PG_IP}:5432/pageindex

PI_REMOTE_DOCLING_URL=${DOCLING_URL}
PI_REMOTE_DOCLING_TOKEN=${DOCLING_TOKEN}
EOF

chmod 600 "$OUT"
echo "wrote $OUT (mode 600)"
echo "  MinIO    ${MINIO_IP}:9000   presign: ${PUBLIC:-<none>}${PRESIGN_PREFIX}"
echo "  Redis    ${REDIS_IP}:6379"
echo "  Postgres ${PG_IP}:5432"
echo "  Docling  ${DOCLING_URL:-<none>}"
echo
echo "Next: make env      # resolve toggles into .env.active"

[ -n "$PUBLIC" ] || cat <<'WARN'

NOTE: PI_REMOTE_MINIO_PUBLIC_ENDPOINT is empty, so the remote Docling service
cannot fetch presigned URLs — PDF/image ingestion will fail, other formats are
unaffected. Set it to the public MinIO host:

  PI_REMOTE_MINIO_PUBLIC_ENDPOINT=minio.example.com ./scripts/make_remote_env.sh

See docs/ENV_PROFILES.md.
WARN
